language: julia
os:
  - linux
  - osx
julia:
  - 1.3
  - 1.5
  - nightly
notifications:
  email: false
git:
  depth: 99999999

after_script:
  - julia -e 'using Pkg, Admixture; cd(joinpath(dirname(pathof(Admixture)), "..")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder()); Coveralls.submit(process_folder())'

jobs:
  allow_failures:
    - julia: nightly    
  include:
    - stage: "Documentation"
      julia: 1.5
      os: linux
      script:
        - julia -e 'using Pkg; Pkg.add("Documenter")'
        - julia -e 'using Admixture; include(joinpath(dirname(pathof(Admixture)), "..", "docs", "make.jl"))'
      after_script: skip
      after_success: skip  
      