# compute this using
# using Tar, Inflate, SHA
# filename = "download?version=4" # I just used wget for the URL below and this is how it saved it
# println("sha256: ", bytes2hex(open(sha256, filename)))
# println("git-tree-sha1: ", Tar.tree_hash(IOBuffer(inflate_gzip(filename))))
[[ADMIXTURE]]
arch = "x86_64"
git-tree-sha1 = "316b9c66aef8f67001d54aa86a244d1e769c1e1a"
os = "linux"

    [[ADMIXTURE.download]]
    sha256 = "353e8b170c81f8d95946bf18bc78afda5d6bd32645b2a68658bd6781ff35703c"
    url = "http://dalexander.github.io/admixture/binaries/admixture_linux-1.3.0.tar.gz"

[[ADMIXTURE]]
arch = "x86_64"
git-tree-sha1 = "4e9c4e9d7c5c66318a2e99f29a479aee6630e4ff"
os = "macos"

    [[ADMIXTURE.download]]
    sha256 = "20573453d788e33c01a2756bd9200fd146adf8918b9bb4013d307055926331fc"
    url = "http://dalexander.github.io/admixture/binaries/admixture_macosx-1.3.0.tar.gz"
